<?php

/**
 * Simple service container for the entityhelper module.
 *
 * @property EntityHelperChanged $EntityHelperChanged
 * @property EntityHelperGet $EntityHelperGet
 * @property EntityHelperSet $EntityHelperSet
 * @property EntityHelperWrapper $EntityHelperWrapper
 * @property EntityHelperTaxonomy $EntityHelperTaxonomy
 * @property EntityHelperDropdown $EntityHelperDropdown
 */
class EntityHelperContainer extends AbstractPPContainer {}